### PR TITLE
fix(groom): page the dispatcher's real termination reason, not the EC2 state

### PR DESCRIPTION
**Pull request by cipher813**
> **DRAFT — must not merge before `nousergon-lib-PR287`.** The `reason=` argument this PR passes does not exist in the currently pinned lib (`v0.124.27`), so merging out of order breaks every groom dispatch with a `TypeError`. The pin bump is the only remaining commit and lands as soon as PR287 merges and autobumps the version.

## What this fixes

The lane reconciler could only see EC2 instance state, so it restated that state as if it were a diagnosis:

```
🔴 Groom lane DEATH — lane-died: instance i-0f5c55a3e3b26f2ae is shutting-down
   — not in ('pending', 'running')
```

`shutting-down` is equally true of a spot reclaim, a completed run winding down, and this Lambda's own terminate after a failed bootstrap. On 2026-08-03 eleven boxes were torn down here after `RuntimeError: SSM agent not Online after 180s`, and every page carried the wording above. Two groom cycles were spent looking for a groom defect that did not exist — the real fault was a VPC endpoint with private DNS on a Cloudflare-only SG (alpha-engine-config-I6190).

## What it does

- **Producer half** — both `except` blocks in `_launch_groom_spot` pass the exception into `_terminate_instance`, which forwards it to `spot_dispatch.terminate_on_failure(reason=...)`.
- **Consumer half** — the reconciler's `describe_instances` reads the `termination-reason` tag and, when present, pages `dispatcher terminated instance <id> before bootstrap — <reason>`.
- **Unchanged for reclaims** — an untagged instance keeps the existing state-based wording exactly, so genuine spot-reclaim reporting is untouched.
- The tag key comes from `spot_dispatch.TERMINATION_REASON_TAG`, not a local literal, so producer and consumer cannot drift.
- `dedup_key` is deliberately untouched: it is keyed on `run_token`, not the message body, so enriching the text does not change dedup behaviour.

Also initialises `_FakeEc2.tags_created`, which `create_tags` appended to without it ever being defined — an `AttributeError` waiting for the first test to exercise the tag path. This PR is that first test.

## Test plan

`pytest infrastructure/lambdas/scheduled-groom-dispatcher/test_handler.py` — **177 passed**, run against `nousergon-lib` installed from the PR287 branch. `pytest tests/test_lib_pin_lockstep.py` — 4 passed.

Four new tests, three of which fail against `origin/main` with `TypeError: terminate_on_failure() got an unexpected keyword argument 'reason'`:

- the page names the dispatcher's reason and does **not** restate the EC2 state
- the reason also reaches the `groom/_control/reconciled/<token>.json` marker every downstream consumer reads
- an untagged (reclaimed) instance keeps the old wording — the no-regression control
- the producer half: a failed `_wait_ssm_online` tags the instance with the real exception *and* still tears the box down

## Cross-repo

Part of **alpha-engine-config-I6199**. Merge order: **`nousergon-lib-PR287` first**, then this PR.

Closes #6199

**Prepared by:** _Opus 5 (1M context)_ via [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by cipher813** [comment]
**`test` is RED BY DESIGN on this PR.**

Which: `test / Run ALL lambda handler tests`.
Why: the only failure is `TypeError: terminate_on_failure() got an unexpected keyword argument 'reason'` at `index.py:1968`. CI installs the currently pinned `nousergon-lib@v0.124.27`, which predates the argument this PR passes. Verified as the sole cause by reading the failed-job log — no other assertion fails.

Unblocking step, in order:
1. Merge **nousergon-lib-PR287** (green: pytest on py3.9–3.13, pyright, CodeQL, audit, version-untouched guard).
2. Bump the `nousergon-lib@` pin in this repo to the version that merge autobumps to, across every surface `tests/test_lib_pin_lockstep.py` guards.
3. `gh pr ready` this PR — `test` goes green on the same commit.

Locally, with `nousergon-lib` installed from the PR287 branch: **177 passed** in `infrastructure/lambdas/scheduled-groom-dispatcher/test_handler.py`, 4 passed in `tests/test_lib_pin_lockstep.py`.

**Comment by cipher813** [comment]
Gate cleared. `gate:dependency` + `blocked:gate` removed after verifying the blocker is actually resolved, not merely stale:

- **nousergon-lib-PR287 merged** at 2026-08-03T16:27:00Z, autobumped to **v0.124.33**.
- Pin bumped to `v0.124.33` across all **28** surfaces `tests/test_lib_pin_lockstep.py` guards (Dockerfile, requirements.txt, requirements-daily-news.txt, deploy-infrastructure.yml, and each per-Lambda requirements.txt). No `v0.124.2x` reference remains outside the test's own historical comments.
- **181 passed** (`test_lib_pin_lockstep` + `scheduled-groom-dispatcher/test_handler`) against v0.124.33 installed from merged `main` — the `TypeError: unexpected keyword argument 'reason'` that made `test` red by construction is gone.

Note for anyone reading the history: the first local run after the merge showed 5 failures, which were a stale editable install of the lib pointing at a pre-merge checkout, not a code defect. Re-verified after `git pull` — `spot_dispatch.TERMINATION_REASON_TAG` resolves and the suite is green.
